#!/usr/bin/env python3
"""
convert_pdf.py - Preprocesses lecture PDF into clean Markdown text and extracts visual images/diagrams into /assets.
"""
import sys
import os
import re
import argparse
from pathlib import Path
import pdfplumber
import pypdfium2 as pdfium
from PIL import Image

def sanitize_filename(name: str) -> str:
    name = re.sub(r'[^a-zA-Z0-9_\-\s]', '', name)
    name = re.sub(r'\s+', '_', name).strip('_')
    return name.lower()[:50]

def convert_pdf_to_markdown(pdf_path: Path, out_dir: Path, assets_dir: Path, scale: float = 2.0, doc_name: str = None):
    out_dir.mkdir(parents=True, exist_ok=True)
    assets_dir.mkdir(parents=True, exist_ok=True)
    
    stem = doc_name if doc_name else sanitize_filename(pdf_path.stem)
    md_output_path = out_dir / f"{stem}_converted.md"
    
    pypdf_doc = pdfium.PdfDocument(str(pdf_path))
    total_pages = len(pypdf_doc)
    
    md_lines = []
    md_lines.append(f"# Converted Source: {pdf_path.name}")
    md_lines.append(f"> Auto-generated by `convert_pdf` skill. Total pages: {total_pages}.\n")
    
    extracted_visuals = []

    with pdfplumber.open(str(pdf_path)) as plumber_doc:
        for idx, page in enumerate(plumber_doc.pages):
            page_num = idx + 1
            text = page.extract_text() or ""
            text_lines = [l.strip() for l in text.splitlines() if l.strip()]
            
            first_line = text_lines[0] if text_lines else f"Page_{page_num}"
            sanitized_title = sanitize_filename(first_line) if first_line else f"page_{page_num}"
            
            md_lines.append(f"## Page {page_num}: {first_line}\n")
            
            # Detect images or vector drawings (diagrams, flowcharts, trees, DFDs)
            drawings_count = len(page.curves) + len(page.lines) + len(page.rects)
            has_visuals = len(page.images) > 0 or drawings_count >= 10
            
            if has_visuals and page_num > 1:
                pdfium_page = pypdf_doc[idx]
                pil_image = pdfium_page.render(scale=scale).to_pil()
                
                img_filename = f"page_{page_num}_{sanitized_title}.png"
                img_path = assets_dir / img_filename
                pil_image.save(str(img_path))
                
                caption = f"Slide {page_num}: {first_line}"
                md_lines.append(f"![[{img_filename}]]\n*{caption}*\n")
                extracted_visuals.append(img_filename)
            
            if text_lines:
                md_lines.append("```text")
                for line in text_lines:
                    md_lines.append(line)
                md_lines.append("```\n")
            else:
                md_lines.append("*(No text detected on this page - visual slide)*\n")
                
            md_lines.append("---\n")
            
    md_content = "\n".join(md_lines)
    md_output_path.write_text(md_content, encoding="utf-8")
    
    return md_output_path, len(extracted_visuals)

def main():
    parser = argparse.ArgumentParser(description="Convert PDF to text/Markdown and extract images to assets folder.")
    parser.add_argument("--pdf", "-p", required=True, help="Path to source PDF file")
    parser.add_argument("--out-dir", "-o", default="./output", help="Directory to save converted markdown note")
    parser.add_argument("--assets-dir", "-a", help="Directory to save extracted images (default: <out-dir>/assets)")
    parser.add_argument("--doc-name", "-n", help="Base name for the converted markdown file")
    parser.add_argument("--scale", "-s", type=float, default=2.0, help="Resolution scale factor for visual renders")
    args = parser.parse_args()
    
    pdf_path = Path(args.pdf)
    if not pdf_path.is_file():
        print(f"Error: PDF file not found: {pdf_path}", file=sys.stderr)
        sys.exit(1)
        
    out_dir = Path(args.out_dir)
    assets_dir = Path(args.assets_dir) if args.assets_dir else out_dir / "assets"
    
    converted_md, num_visuals = convert_pdf_to_markdown(pdf_path, out_dir, assets_dir, args.scale, args.doc_name)
    print(f"SUCCESS: Converted {pdf_path.name} -> {converted_md}")
    print(f"ASSETS: Extracted {num_visuals} visual figures to {assets_dir}")

if __name__ == "__main__":
    main()
